apiVersion: v1
kind: ServiceAccount
metadata:
  name: dbward-server
  namespace: dbward
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dbward-agent
  namespace: dbward
automountServiceAccountToken: false
