{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dbward.fullname" . }}-secrets
  labels:
    {{- include "dbward.labels" . | nindent 4 }}
type: Opaque
stringData:
  agent-token: {{ .Values.secrets.agentToken | quote }}
  database-url: {{ .Values.secrets.databaseUrl | quote }}
{{- end }}
