apiVersion: v1
kind: Service
metadata:
  name: {{ include "dbward.fullname" . }}-server
  labels:
    app.kubernetes.io/name: {{ include "dbward.fullname" . }}-server
    {{- include "dbward.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "dbward.fullname" . }}-server
