{{- if .Values.server.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dbward.fullname" . }}-server-data
  labels:
    {{- include "dbward.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.server.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.server.persistence.size }}
  {{- if .Values.server.persistence.storageClass }}
  storageClassName: {{ .Values.server.persistence.storageClass }}
  {{- end }}
{{- end }}
