{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dbward.fullname" . }}-server
  labels:
    {{- include "dbward.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dbward.fullname" . }}-agent
  labels:
    {{- include "dbward.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
